name: error

on:
    pull_request:
        branches: [ master ]
    
jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Echo Error
          run: echo ERROR
        - name: Only run this if file README exists
          run: '(test -f README2.md && echo README exists) || echo "::error::Error is thrown here message"
